name: ci
on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1.3.0
        
      - name: Check
        run: |
          cargo check
    